/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentBtn: typeof import('./src/components/header/ContentBtn.vue')['default']
    DesktopNav: typeof import('./src/components/header/DesktopNav.vue')['default']
    IntegrationCard: typeof import('./src/components/home/IntegrationCard.vue')['default']
    IntegrationSection: typeof import('./src/components/home/IntegrationSection.vue')['default']
    MobileNav: typeof import('./src/components/header/MobileNav.vue')['default']
    NavContentCard: typeof import('./src/components/header/NavContentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestimonyCarousel: typeof import('./src/components/home/TestimonyCarousel.vue')['default']
    TheFooter: typeof import('./src/components/footer/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/header/TheHeader.vue')['default']
    TheHumburger: typeof import('./src/components/TheHumburger.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    WorkflowCard: typeof import('./src/components/home/WorkflowCard.vue')['default']
  }
}
