/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    'ActivateAccount': RouteRecordInfo<'ActivateAccount', '/auth/account/activate/:uid/:token', { uid: ParamValue<true>, token: ParamValue<true> }, { uid: ParamValue<false>, token: ParamValue<false> }>,
    'AcceptInvite': RouteRecordInfo<'AcceptInvite', '/auth/account/activate/invite/:uid/:token', { uid: ParamValue<true>, token: ParamValue<true> }, { uid: ParamValue<false>, token: ParamValue<false> }>,
    'Login': RouteRecordInfo<'Login', '/auth/login', Record<never, never>, Record<never, never>>,
    'ForgotPassword': RouteRecordInfo<'ForgotPassword', '/auth/password/reset', Record<never, never>, Record<never, never>>,
    'ResetPassword': RouteRecordInfo<'ResetPassword', '/auth/password/reset/:uid/:token', { uid: ParamValue<true>, token: ParamValue<true> }, { uid: ParamValue<false>, token: ParamValue<false> }>,
    'Register': RouteRecordInfo<'Register', '/auth/register', Record<never, never>, Record<never, never>>,
    'RegistrationComplete': RouteRecordInfo<'RegistrationComplete', '/auth/register/done', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    'MySummary': RouteRecordInfo<'MySummary', '/home/my-summary', Record<never, never>, Record<never, never>>,
    'PortfolioSummary': RouteRecordInfo<'PortfolioSummary', '/home/portfolio-summary', Record<never, never>, Record<never, never>>,
    'HomeCalendar': RouteRecordInfo<'HomeCalendar', '/home/task/calendar', Record<never, never>, Record<never, never>>,
    'HomeFiles': RouteRecordInfo<'HomeFiles', '/home/task/files', Record<never, never>, Record<never, never>>,
    'HomeBoard': RouteRecordInfo<'HomeBoard', '/home/task/kanban-board', Record<never, never>, Record<never, never>>,
    'HomeTasks': RouteRecordInfo<'HomeTasks', '/home/task/list', Record<never, never>, Record<never, never>>,
    'team-summary': RouteRecordInfo<'team-summary', '/home/team-summary', Record<never, never>, Record<never, never>>,
    '/portfolio': RouteRecordInfo<'/portfolio', '/portfolio', Record<never, never>, Record<never, never>>,
    'Portfolio': RouteRecordInfo<'Portfolio', '/portfolio', Record<never, never>, Record<never, never>>,
    'projects-detail-dashboard': RouteRecordInfo<'projects-detail-dashboard', '/portfolio/dashboard/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'projects-detail-gantt': RouteRecordInfo<'projects-detail-gantt', '/portfolio/gantt/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'projects-detail-board': RouteRecordInfo<'projects-detail-board', '/portfolio/kanban-board/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ProjectTasks': RouteRecordInfo<'ProjectTasks', '/portfolio/list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/team': RouteRecordInfo<'/team', '/team', Record<never, never>, Record<never, never>>,
    'Team': RouteRecordInfo<'Team', '/team', Record<never, never>, Record<never, never>>,
    '/timesheet': RouteRecordInfo<'/timesheet', '/timesheet', Record<never, never>, Record<never, never>>,
    'Timesheet': RouteRecordInfo<'Timesheet', '/timesheet', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
